### ISSUE TITLE
PHP Notice:  Undefined index

### ISSUE THREAD

**Issue by ghost** [PromisePay/promisepay-php#32]
`PHP Notice:  Undefined index: items in promisepay/promisepay-php/lib/ItemRepository.php on line 15`

I believe the API returns empty array when the offset yields no items.
Is this a bug or a feature?

It's probably not safe to do `$arr['key']` when `'key'` is not guaranteed to be there at all scenarios...

**Comment by NinoSkopac** [comment]
Hey @limtaesu .

Can you please post some code, so I can try to reproduce the issue?

Thanks in advance.
Nino

**Comment by NinoSkopac** [comment]
Hi @ghost,

I have reviewed this and I can tell you it's fixed.

At the time when this issue was opened, this is what ItemRepository:15 looked like: https://github.com/NinoSkopac/promisepay-php/blob/f960a9a8b1560893fd8d69310f168440dc3ba5c0/lib/ItemRepository.php#L15. In other words, there were no `isset()` checking, but this is now done inside `PromisePay::getDecodedResponse()`.
